# Generated by Django 4.1.4 on 2022-12-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(default='09171241720', max_length=11),
            preserve_default=False,
        ),
    ]
