# Generated by Django 4.1.4 on 2022-12-26 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_customer_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_claimed',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 26, 4, 41, 34, 836368, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_required',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 26, 4, 41, 41, 71305, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='remarks',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
    ]
