# Generated by Django 4.1.4 on 2023-01-03 16:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_paymentoption_transaction_payment_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 1, 3, 16, 31, 6, 721725, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'Not paid'), (1, 'Downpayment received'), (2, 'Fully paid')], default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('num_of_serviced_wash_loads', models.IntegerField()),
                ('num_of_serviced_dry_loads', models.IntegerField()),
                ('service_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('detergent_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fabcon_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bleach_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('plastic_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_method', models.PositiveSmallIntegerField(choices=[(0, 'Cash'), (1, 'GCash')], default=0)),
                ('payment_made', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_required', models.DateTimeField(blank=True, null=True)),
                ('date_claimed', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='inventory.customer')),
            ],
        ),
    ]
