# Generated by Django 4.1.4 on 2023-01-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_invoice_customer_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='num_of_serviced_dry_loads',
        ),
        migrations.RemoveField(
            model_name='order',
            name='num_of_serviced_wash_loads',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service_cost',
        ),
        migrations.AddField(
            model_name='order',
            name='dry_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='wash_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
    ]
