# Generated by Django 4.1.4 on 2023-01-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_order_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unpaid'), (1, 'Cash'), (2, 'GCash')], default=1),
        ),
    ]
