# Generated by Django 4.1.4 on 2023-01-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service_cost',
        ),
        migrations.AddField(
            model_name='order',
            name='dry_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='wash_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
