# Generated by Django 4.1.4 on 2023-02-05 07:34

from django.db import migrations
from django.db.models import F


def forwards_func(apps, schema_editor):
    Order = apps.get_model('inventory', 'Order')
    Order.objects.update(
        service_cost=F('wash_cost') + F('dry_cost')
    )


def backwards_func(apps, schema_editor):
    # No backwards migration without extra calculations and parsing made
    # on remarks. Passing for now.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_order_service_cost'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func)
    ]
