# Generated by Django 4.1.4 on 2023-02-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_migrate_dry_and_wash_cost_to_service_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dry_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='wash_cost',
        ),
    ]
